### ISSUE TITLE
Intermittent receive

### ISSUE THREAD

**Issue by steveww** [etrombly/RFM69#11]
I have the RFM69HW module all wired up OK. My code can chat to the board, get temperature, registers etc. My code is just running a simple receive loop and my Arduino transmitter is sending a small packet every 8 seconds. I have tested this with another board I have all is good. The Python code is only picking up these packets very intermittently, with long periods of not receiving then just the odd packet gets through, sometimes more than one packet at the same time! How is this possible when they are only been sent every 8 seconds. Any ideas?

**Comment by etrombly** [comment]
I was actually seeing similar issues and haven't had a chance to track it down. I don't have my rfm69 hooked up directly to the pi anymore, I have it hooked up through a arduino on serial. If I get a chance I'll try to hook it back up and troubleshoot again, but it may be a little while. I'll leave this issue open until I get it resolved.

**Comment by steveww** [comment]
Thanks for the reply. I think I will take a similar approach. I will put a moteino on a Pi HAT and have them chat over I2C.

**Comment by secretbatcave** [comment]
Greetings. 

I too was having this problem, however I think I've fixed it with #12

**Comment by etrombly** [comment]
fixed by https://github.com/etrombly/RFM69/pull/12
