### ISSUE TITLE
Interfering with File Append?

### ISSUE THREAD

**Issue by klhowells** [etrombly/RFM69#13]
I successfully used the RFM69 library to communicate between RFM69HCW's running on an Arduino UNO and a Respberry Pi 3, running your example.py on the RasPi.  Running example.py, after the register info and setting notes and finally 'listening' I see a steady stream of message lines from the Arduino.
Thanks for the library!

I want to save the text messages coming from the Arduino. I tried
pi@raspberry:~ $ example.py > wirelessData.txt
but the resulting file only contained all the register info etc. and after 'listening' only the first message received from the Arduino. This despite seeing a screen full of messages before shutting the script down.
I altered the example.py code to open a file (for append) and then just after the print command in the while True: block at the end I added a file.write() command (first making a string with the content of the print command).  I run the example.py script and see line after line of data coming from the Arduino but only the first line of data ever gets written to the file. I even added a counter and an if statement so it doesn't write the first received line but then I only get the second received line in the file. 

Do you have any idea what the problem is? I really want to be able to DO something with the data I get wirelessly.

**Comment by etrombly** [comment]
not sure what is causing the initial issue with redirecting to a file. While using file.write() from python it may be buffering. You could try:
output_file = file.open("/output/file/location", buffering = 0)

or you can add a newline to the output when you call file.write() (print adds a newline automatically).

**Comment by klhowells** [comment]
Thanks for the quick response. Already explored buffering issues. Noticed that the file written to had the cursor at the end of the (single) line despite my having specifically added a \n before writing.
Tried having it just write the first 8 characters of each received line and it worked! - each received message was written to the file. Changed the code to take a slice of the string from 0 to len()-1 and was getting the entire message line stored to the file. When I have time I'll look to see what that lopped-off character actually was. Whatever is the last item in the test.DATA[] array.

Thanks again for creating this library!
