### ISSUE TITLE
Almost working with OrangePi

### ISSUE THREAD

**Issue by jorgenlarsson** [etrombly/RFM69#14]
Hi,
First off, thank you for your contributions and this port.
I am trying to get your library to work with OrangePiOne (Allwinner H3). I have modified the RFM69.py with this gpio library https://github.com/duxingkei33/orangepi_PC_gpio_pyH3.
When I am running the example.py, the RFM69s on my arduinos are receiving fine, but I can't get the OrangePi to receive. Not from the Arduinos, not from the OrangePiPC, running your example.py (a bit modified). interrupt pin is OK (it will not work without it connected). I think there is an issue with the way the interrupt is handled by your library/Rpi.GPIO that is not working with the GPIO library I am using. I have looked at the RPi.GPIO library, to see if I can make it work with the OrangePi, but I have not had any luck. The issue is probably in the interruptHandler, but I cannot find a workaround. Beacuse this is not supported in the OPi library, I had to comment out the lines 127 and 128:
 #GPIO.remove_event_detect(self.intPin)
 #GPIO.add_event_detect(self.intPin, GPIO.RISING, callback=self.interruptHandler)

I am quite new to this kinds of issues, so after a couple of days of digging and trying, I hope some of you could point me in the right direction.

Thank you,

Jørgen Larsson

**Comment by etrombly** [comment]
Since the library you are using doesn't have event handling, probably the best solution would be to modify the library to have a separate thread that just checks the interrupt pin and calls the interruptHandler function of the pin goes high.

**Comment by etrombly** [comment]
closing this since there hasn't been a response and I don't have an orangepi to test with

**Comment by LDavidFr** [comment]
Hi, 
I am very interested in this library RFM69 orangePi.
If you were kind, send it to me: D
