### ISSUE TITLE
Could you please post a very simple example of using the "struct_receive" method?

### ISSUE THREAD

**Issue by peterfosseus** [etrombly/RFM69#15]
Hi,

I am trying to use the struct method used by Felix in his Struct_send and Struct_receive examples.
But my Python is not strong enough to figure out the correct syntax for the Struct_Receive part in Python using your library. Is there any chance you could give an example of a struct_receive, please.
Could it you please use "int" and "long" and "float" in the example, that would be fantastic :)

I defined a class for the struct i am sending from Arduino/Moteino:
typedef struct { 
   int code          = 01;
   int realPower_CT1 = 0;
   int realPower_CT2 = 0;
   int realPower_CT3 = 0;
   int realPower_CT4 = 0; 
   long wh_CT1       = 0.0;
   long wh_CT2       = 0.0;
   long wh_CT3       = 0.0;
   long wh_CT4       = 0.0; 
} Tx_struct; 

Tx_struct tx_data;

and send it like this:
   if (radio.sendWithRetry(GATEWAYID, (const void*)(&tx_data), sizeof(tx_data))) 

After many hours of Googling I tried this in my Python receive program:

class Tx_struct(Structure):
    _fields_ = [
       ("code", c_int),
       ("realPower_CT1", c_int),
       ("realPower_CT2", c_int),
       ("realPower_CT3", c_int),
       ("realPower_CT4", c_int),
       ("wh_CT1", c_long),
       ("wh_CT2", c_long),
       ("wh_CT3", c_long),
       ("wh_CT4", c_long)]

tx_data = Tx_struct

But now I don't know how to pass it to radio.sendWithRetry() in my Python program to send it back to the Moteino ?

Thank you very much for the library.
-pete

**Comment by etrombly** [comment]
Sorry it took me so long to reply. A good example is in my gateway library https://github.com/etrombly/gateway/ . If you look in gateway.py at the message class you should be able to see how to use the Struct library to pack and unpack a struct.

**Comment by peterfosseus** [comment]
Thank you, 
I was having trouble with getting reliable bi-directional messages using the RFM69 directly connected to the Pi. (Probably something to do with running it on a multitasking OS, I did try a Linux-rt kernel, it made a slight improvement but got me thinking that I can/should do the timing critical stuff on a second uP)
I have since re-designed my project and put a second Moteino in as the controller, will use your gateway example, on the Pi, to do MQTT for graphing and such.
Thank you for all your work.
