### ISSUE TITLE
RFM69 Hangs While Syncing?

### ISSUE THREAD

**Issue by Donny3000** [etrombly/RFM69#16]
First off, thank you for your contributions to making a nice Python interface for the RFM69 radio! This is a great piece of work! I'm trying to get the example.py to run on my RPi, but the RFM69 class seems to hang in the init method when syncing.  I can seem to read values from the registers fine, but I can't seem to write to them. Have you experienced this issue?

**Comment by Donny3000** [comment]
#17 is the solution I submitted for this issue.  It appears all the uC's have a hard reset routine, so I embedded linux shouldn't be any different.  This will allow the RPi to sync up and continue with initialization.

**Comment by etrombly** [comment]
Merged your request, so closing this. Thanks
