### ISSUE TITLE
Raspberry Pi 3 <-> Dragino Lora Arduino Shield v1.3

### ISSUE THREAD

**Issue by mkharibalaji** [etrombly/RFM69#19]
Hi @etrombly ,
          I found this library a damn good one but unfortunately not able to make it work with this combo,
I have connected everthing as per your pin configuration using Raspberry pi 3 with Dragino Lora Arduino Shield v1.3 (The board with Jumper Settings and Antenna holder - http://wiki.dragino.com/index.php?title=Lora_Shield)
Dragino Lora arduino shield pin - Pi pin
3v3 - 17
DIO0 - 18 (GPIO24)
MOSI - 19
MISO - 21
CLK - 23
NSS - 24
Ground - 25
RESET - 29

When i run the code...the RFM69 is not able to initialize.It just gets stuck before the while loop (i.e.,the while loop is kept on running) found in RFM69.py in the init section
       ..............
       ................
        #verify chip is syncing?
        while self.readReg(REG_SYNCVALUE1) != 0xAA:
            self.writeReg(REG_SYNCVALUE1, 0xAA)

I am totally a newbie to this kind of stuff.It would be great if you could help me whether am i making any mistake ?

Your help is much appreciated.

Thanks & regards,
Hari

**Comment by etrombly** [comment]
This library is for the rfm69, the Dragino Lora uses a RFM95. They aren't compatible. Looks like a neat board though, but I don't have one to port a library with. here's some info on the differences, https://learn.adafruit.com/adafruit-rfm69hcw-and-rfm96-rfm95-rfm98-lora-packet-padio-breakouts/overview
