### ISSUE TITLE
ENER314-RT RFM69W module

### ISSUE THREAD

**Issue by jiteshvassa** [etrombly/RFM69#23]
Just wondered if it would take much work to make use of this library with the following RFM69W module:

https://energenie4u.co.uk/res/pdfs/ENER314-RT%20User%20Guide%20V2.pdf

The second page shows that the wiring is a little different to what's mentioned in the project readme.

**Comment by etrombly** [comment]
have you tried pyenergenie https://github.com/whaleygeek/pyenergenie ? Looks like it supports it. If not you should be able to just swap out the pin definitions.

**Comment by etrombly** [comment]
closing because no response
