### ISSUE TITLE
Include a license

### ISSUE THREAD

**Issue by losttime** [etrombly/RFM69#3]
I'm a little unclear about how this code can be used in my projects. Can you include a license so I know what I can and can't do?

This is a port of the LowPowerLabs RFM69 library, which is GPLv3. That would imply this library must be GPLv3 as well.

This library also depends on spidev, which is GPLv2 (not "or any later version"). Depending on who you ask, that would mean this library should be GPLv2.

This library can't be both GPLv2 and v3. As library owner, can you make that call and/or talk to the respective license holders about using one license version over the other?

**Comment by etrombly** [comment]
I'll have to check with the spidev people I guess. I have no problem with it being GPLv3, but don't think I can make that call at this point. I'll get back to you.

**Comment by etrombly** [comment]
Opened issue with spidev project to add GPLv2 or higher license. I believe he may have misunderstood me, because he just included the v2 license. By referencing the issue I feel comfortable licensing this as v3 though. https://github.com/doceme/py-spidev/issues/16
